### ISSUE TITLE
Major Bug: The Xbox Mouse pointer is followed by the Pointer on PC but not a mouse directly connected to Xbox.

### ISSUE THREAD

**Issue by ssquadteam** [unknownskl/xbox-xcloud-client#923] opened 2023-08-25 15:47 UTC

**Comment by unknownskl** [comment] 2023-08-27 00:03
This is a new feature for apps like edge. Is there a specific use case which causes this to be a problem?

**Comment by ssquadteam** [comment] 2023-08-27 08:43
> This is a new feature for apps like edge. Is there a specific use case which causes this to be a problem?

For Example all I use the app is for sharing Audio between my PC and Xbox cause AUX here has a lot of Ground Loop.

When I play Cod for Example with KBM, It wants to follow the Cursor on Linux and even after disconnecting the Mouse it just won't work and the Cursor will still go to where it last was on PC.

There should be a toggleable button for it.

**Comment by J0E6469** [comment] 2023-08-28 13:22
It would be nice for the mouse pointer to disappear shortly after not touching the mouse, too.

**Comment by unknownskl** [comment] 2023-08-29 14:55
I am unable to replicate it in other games but will add an option in the settings to turn off the mouse integration.

**Comment by ssquadteam** [comment] 2023-08-29 15:25
ye please, i wanna use Mic

**Comment by unknownskl** [comment] 2023-08-30 08:10
A new options has been added to enable and disbale the mouse keyboard integration. It will be disabled by default. Please let me know if this fixes your problems.
Note that the mic integration is still experimental. A known issue is that the voice's pitch is too high, this will be tackled in the next update

**Comment by ssquadteam** [comment] 2023-08-30 09:55
> A new options has been added to enable and disbale the mouse keyboard integration. It will be disabled by default. Please let me know if this fixes your problems. Note that the mic integration is still experimental. A known issue is that the voice's pitch is too high, this will be tackled in the next update

ye I tried the experimental build, only issue I found so far is that the Stuff I say for like 3 seconds get repeated on the 4th second mark for example and everything plays as if a tts was speaking at 3x speed. Note my Xbox and PC are connected via Ethernet to each other and PC is sharing the Network to the Xbox so there should be no delay

**Comment by NT83** [comment] 2023-09-05 20:19
I don't know if this is related as I don't really understand the issue of OP. But there is a game on XBOX where we see both mouse and controller in use. This is PALADINS. On the home screen you see double pointer, the mouse and where the joystick of the controller goes... It sometimes blocks the controls on screen in the menu.

however with the options to disable mouse and keyboard, the issue I describe is gone.

**Comment by unknownskl** [comment] 2023-10-02 16:13
I assume the issue is fixed with the option to enable / disable the keyboard and mouse integration. The mic chat should also be fixed in the 2.0.0-beta14.

**Closed as completed by unknownskl** 2023-10-02 16:13 UTC
