### ISSUE TITLE
Javascript error in main process

### ISSUE THREAD

**Issue by sagarwadhwa1** [unknownskl/xbox-xcloud-client#699] opened 2023-01-25 08:49 UTC
Stack Trace : 
Uncaught Exception:
TypeError: Cannot read properties of undefined (reading 'getProvider')
at IpcMainImpl.<anonymous> (/Applications/Greenlight.app/Contents/Resources/app.asar/app/background.js:1:72804)
at IpcMainImpl.emit (node:events:527:28)
at EventEmitter.<anonymous> (node:electron/js2c/browser_init:165:11237)
at EventEmitter.emit (node:events:527:28)

Happens as soon as I open the app and it logs in (if i'm already logged in)
Version : 2.0.0-beta2

**Comment by Blackflexxy** [comment] 2023-01-25 08:54
I think it's because xCloud isn't supported in your country, try vpn

**Comment by unknownskl** [comment] 2023-02-11 00:07
Duplicate of #510. The new release 2.0.0-beta3 should fix the error

**Closed by unknownskl** 2023-02-11 00:07 UTC
